<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__re_IDnumber</name>
   <tag></tag>
   <elementGuidId>c7701b96-71b9-43b7-b09c-64371d5b0f0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re_IDnumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#re_IDnumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93a4bcb8-5713-4db5-b2b0-8d406cc57926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>256102cf-8abc-415d-b60c-2788ca04043b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re_IDnumber</value>
      <webElementGuid>b3e67540-6130-4bbb-af8c-a3c38c3cd00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fce94a33-9fc6-4bcf-80b9-61823d4f44c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re_IDnumber</value>
      <webElementGuid>f2152b23-0ec9-4829-9c07-ec6d1f426160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>คำตอบของคุณ</value>
      <webElementGuid>f4d08a98-7697-4c08-a0bc-666127a1466e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re_IDnumber&quot;)</value>
      <webElementGuid>0c13d7a1-15e2-4a43-a58e-9ffd6e144b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re_IDnumber']</value>
      <webElementGuid>875d2f6e-bce2-472e-ba4b-c119efb68a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>86fadea7-4be6-4e11-bec2-55f1c34bbd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 're_IDnumber' and @id = 're_IDnumber' and @placeholder = 'คำตอบของคุณ']</value>
      <webElementGuid>b99b7851-81be-48d4-8d67-9ad2f42d1175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
