<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__re_phonenumber</name>
   <tag></tag>
   <elementGuidId>b702ffdf-2721-4bac-8019-bd2f81be5be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re_phonenumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#re_phonenumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9a2770-cd7d-479b-960f-df91a8f635dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cb6f1a5-02d8-4130-9d10-3fe4a5503d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re_phonenumber</value>
      <webElementGuid>4408885b-646b-4cb3-b578-7777a112d3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02d65fab-f774-44d9-8983-f3d081b4503b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re_phonenumber</value>
      <webElementGuid>deff54a2-4230-42a6-8bf2-8b8a8200d2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>คำตอบของคุณ</value>
      <webElementGuid>77ead73a-4502-4f10-88fd-22ac070dfc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re_phonenumber&quot;)</value>
      <webElementGuid>6e762534-65f0-4992-aecb-8dc2fc7095d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re_phonenumber']</value>
      <webElementGuid>05efea37-b7ed-4795-9414-b01a2a6e5063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>ab0c41ed-6321-4032-8c0b-a8c82e201141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 're_phonenumber' and @id = 're_phonenumber' and @placeholder = 'คำตอบของคุณ']</value>
      <webElementGuid>4204b67c-6311-498a-b862-cd24c1c36087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
