<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__re_prefix</name>
   <tag></tag>
   <elementGuidId>160264bb-0f8b-489f-b984-ef399108aa32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re_prefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#re_prefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d460a34-c666-4405-9572-a39144f7b673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>prefixs</value>
      <webElementGuid>cb0e006c-4742-4591-bb62-c4f28d8bdc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re_prefix</value>
      <webElementGuid>57b13663-7716-4bee-8c6f-44474ffd40f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re_prefix</value>
      <webElementGuid>53f1a8b6-25db-44dd-b67a-e2c3d4252fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re_prefix&quot;)</value>
      <webElementGuid>423de48b-03e7-43ba-8e1f-eafe3ec9aa8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re_prefix']</value>
      <webElementGuid>b39fd7f2-1408-4192-a440-df0aa3e7c6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>622c960e-0625-46a1-9fa6-7a2592b8b20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 're_prefix' and @name = 're_prefix']</value>
      <webElementGuid>881558a0-b644-42b6-a284-75720cf75bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
