<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_re_educational</name>
   <tag></tag>
   <elementGuidId>e14109d7-4597-4d94-b356-7268541a2871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re_educational']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#re_educational</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>624b5fbf-aac4-4118-a6d8-9b921ffef644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>educationals</value>
      <webElementGuid>47f4d29d-d498-4830-8b10-d8657263b8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re_educational</value>
      <webElementGuid>d3128677-f7bd-4d0c-ada8-9766be3bb017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re_educational</value>
      <webElementGuid>47594d37-0790-435b-b0d8-3d493ce328dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re_educational&quot;)</value>
      <webElementGuid>dbc8b1db-1770-41dd-9d2a-5b5cf3afc1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re_educational']</value>
      <webElementGuid>8adb5e5f-af84-461e-ab79-511d424f000c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>9fd645e9-595d-4f69-8ab4-00a69f3f29b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 're_educational' and @name = 're_educational']</value>
      <webElementGuid>235e89ed-c454-4818-8ce0-f7435ba27ea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
