<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Demo_vfb-18</name>
   <tag></tag>
   <elementGuidId>423a9545-29d6-4620-9854-82a07a13cbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>574c6baf-f736-490e-98c6-0e8b80e5e96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d9079b6-ac07-4a1b-9e8f-ecfbc9ffd2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>d216f29c-ebeb-4282-920f-2639ed50e280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>33073f9e-6f07-4ba4-8e61-dfd44328bc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-date-picker vfb-medium hasDatepicker</value>
      <webElementGuid>589a5b9e-0319-47d4-9320-cb0450425612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dp-dateformat</name>
      <type>Main</type>
      <value>mm/dd/yy</value>
      <webElementGuid>cee0583b-970c-4be2-b1b8-90182fbbe2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-18&quot;)</value>
      <webElementGuid>5c1f46e2-69cc-478d-9074-d6e89d5bb6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-18']</value>
      <webElementGuid>44a7590d-e865-45a1-9357-bf9f74355b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-18']/span/input</value>
      <webElementGuid>14e17481-ed15-4273-868b-9c19a83b5619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/input</value>
      <webElementGuid>3725b9f5-3b8b-41d8-84ef-c0801388d361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-18' and @id = 'vfb-18']</value>
      <webElementGuid>2aa4cc95-5f14-4d12-93e8-88c7de5008cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
