<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_vfb-13address</name>
   <tag></tag>
   <elementGuidId>229ade9d-156d-4af0-8b89-e5be8d090865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-13-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-13-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>363942e3-7668-4c6d-9507-5473f60d7e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>071e3b18-7ba0-49c7-8107-5802d49428c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-13[address]</value>
      <webElementGuid>898a43cb-d388-4c56-aa9e-4d4efbe1044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-13-address</value>
      <webElementGuid>07d66b5b-1041-4977-879b-4a773700aaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>59808b9e-e6e7-4b7c-8c2e-6ae2c7df70b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium  </value>
      <webElementGuid>1baa0153-86fe-4152-8eb1-dd4cb04e5976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-13-address&quot;)</value>
      <webElementGuid>85dc6908-4aa4-46ed-a2cf-f6298fa0ba6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-13-address']</value>
      <webElementGuid>75214578-0098-49e8-8f65-b8114713f8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span/input</value>
      <webElementGuid>ba021fe8-7584-430b-8f27-48e5a2426d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span/input</value>
      <webElementGuid>e7a9709a-b715-4ed8-9a5d-fc6c4b58ebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-13[address]' and @id = 'vfb-13-address']</value>
      <webElementGuid>231df785-9490-42f3-b4fe-52b2904913d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
