<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>2bf2a35d-154e-450e-94d9-2e54671eb42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'กลับสู่หน้าหลัก')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07f52d8d-a1ef-48e5-a78e-759dd71431d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../view_course.php</value>
      <webElementGuid>4f9078b7-c6ea-4911-9678-c2ed6250f828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>5ffae5b0-d941-400c-99a5-c66a61ca9a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กลับสู่หน้าหลัก</value>
      <webElementGuid>d4c245b6-2621-4596-90bf-49ba9eae75e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>00984fb6-1b9c-4fab-a402-c10cbc1cff53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'กลับสู่หน้าหลัก')]</value>
      <webElementGuid>da9391c2-047e-4b36-ac47-f8202b5bf043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้อมูลอันนี้ได้ถูกเพิ่มลงฐานข้อมูลแล้ว'])[1]/following::a[1]</value>
      <webElementGuid>89d63e7b-e2ba-44a9-aafd-25444740ae9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หลักสูตรระยะสั้น'])[2]/following::a[1]</value>
      <webElementGuid>fdc86920-4d05-4fe9-b3ee-457490abd6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='กลับสู่หน้าหลัก']/parent::*</value>
      <webElementGuid>f011398d-38cc-4362-b8bd-eff42ffd294e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../view_course.php')])[2]</value>
      <webElementGuid>8afdd91a-5198-4597-a46f-5069c41f5f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>bd59d3d5-4ca6-4983-8f43-73b009afe6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../view_course.php' and (text() = 'กลับสู่หน้าหลัก' or . = 'กลับสู่หน้าหลัก')]</value>
      <webElementGuid>757b99be-6ab3-4d1a-a0dc-669dacfc639d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
