<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__card-img-top</name>
   <tag></tag>
   <elementGuidId>e1f6a624-229a-4e22-8324-dcd55cefda59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='...'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3de9fabe-0999-4768-8c3c-85a3d88c1155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>9942bc3f-702f-47f4-8f51-a95bf36ee0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/18.png</value>
      <webElementGuid>0a2b261f-cbf1-48eb-9509-0f05c0dbd036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>312e929b-4224-4615-9cc7-ea3b90bca66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;py-2&quot;]/div[@class=&quot;container-fluid px-4 px-lg-5 mt-5&quot;]/div[@class=&quot;row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-4 justify-content-center&quot;]/div[@class=&quot;col mb-5&quot;]/div[@class=&quot;card h-150&quot;]/a[@class=&quot;card-link&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>11849628-8eeb-4531-bb77-bd589994e534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[16]</value>
      <webElementGuid>0726eaf2-0ae5-4de4-8c24-6c52efca06e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/a/img</value>
      <webElementGuid>7d28d1e9-6621-4125-8f88-932f5a0ef487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/18.png' and @alt = '...']</value>
      <webElementGuid>85980103-b073-48f1-931e-d57b65c50fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
